CC = gcc
CFLAGS = -Wall -g
CPFLAGS = -Wextra
OBJS = 2.10 2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9

.PHONY: all clean 

all: $(OBJS)

2.1: 2.1.c

2.2: 2.2.c

2.3: 2.3.c

2.4: 2.4.c

2.5: 2.5.c

2.6: 2.6.c

2.7: 2.7.c

2.8: 2.8.c

2.9: 2.9.c

2.10: 2.10.c

clean:
	rm -f *~ *.o $(OBJS)

